# Generated by Django 5.1.7 on 2025-03-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_messages',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='text_messages',
        ),
    ]
