# Generated by Django 5.1.6 on 2025-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_zipcode_order_zip_code_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='square_order_id',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
    ]
