# Generated by Django 5.1.5 on 2025-02-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_messages',
            field=models.BooleanField(default=False),
        ),
    ]
