# Generated by Django 5.1.6 on 2025-03-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pre_tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
