# Generated by Django 5.1.7 on 2025-04-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_newsletter_subscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
