# Generated by Django 5.1.7 on 2025-04-15 03:07

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='banner_image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='newsLetterBanner/'),
        ),
    ]
