# Generated by Django 5.1.6 on 2025-04-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_theme_timestamp'),
        ('myapp', '0014_alter_newsletter_banner_image'),
    ]

    operations = [
    ]
