# Generated by Django 5.1.6 on 2025-04-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_merge_20250415_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='dropDate',
            field=models.DateField(),
        ),
    ]
