# Generated by Django 5.1.7 on 2025-04-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="timeStamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
